export const data = {
  academic: {
    major: {
      selected: "Test",
      filterName: "Major",
      data: [
        "Accounting",
        "Art",
        "Arts",
        "Biblical Studies",
        "Biochemistry",
        "Biochemistry: Chemistry",
        "Biology",
        "Business Administration",
        "Chemistry",
        "Christian Ministries",
        "Combined Languages",
        "Communication and Speech Disorders",
        "Communication Arts",
        "Computer Science",
        "Deciding Major",
        "Digitial Literacy/Computer Science",
        "Dual Enrollment",
        "Early Childhood",
        "Early Childhood Education",
        "Earth & Space Science",
        "Economics",
        "Educational Leadership",
        "Elementary",
        "Elementary Art Education",
        "Elementary Education",
        "English",
        "English as a Second Language",
        "English Language and Literature",
        "Finance",
        "Financial Analysis",
        "French",
        "General Science",
        "Grad Finance Non-Degree",
        "Graduate Education - Non-Degree",
        "Graduate Music - Non Degree",
        "History",
        "Humanities",
        "Initial License in Music",
        "International Affairs",
        "Kinesiology",
        "Leadership",
        "Leadership-Christian School Education",
        "Linguistics",
        "Mathematics",
        "Mathematics Specialist",
        "Mathematics/Science",
        "Middle School and Secondary Education",
        "Middle School Education",
        "Moderate Disabilities",
        "Modern Foreign Languages: French",
        "Modern Foreign Languages: Spanish",
        "Music",
        "Music Education",
        "Music Education (Graduate)",
        "Music Performance",
        "Non-Matriculated",
        "Philosophy",
        "Physical & Applied Sciences: Physics",
        "Physics",
        "Pike Honors Program",
        "Political Science",
        "Professional Licensure in Music",
        "Psychology",
        "Reading",
        "Recreation, Sport and Wellness",
        "Secondary Education",
        "Social Science Teacher Education",
        "Social Welfare",
        "Social Work",
        "Sociology",
        "Spanish",
        "Theatre Arts",
      ],
    },
    minor: {
      selected: null,
      filterName: "Minor",
      data: [
        "Accounting",
        "Art",
        "Biblical Studies",
        "Biology",
        "Business Administration",
        "Chemistry",
        "Communication Arts",
        "Computer Science",
        "Economics",
        "English Language and Literature",
        "French",
        "History",
        "Kinesiology",
        "Linguistics",
        "Mathematics",
        "Music",
        "Philosophy",
        "Physics",
        "Pike Honors Program",
        "Political Science",
        "Psychology",
        "Sociology",
        "Spanish",
        "Theatre Arts",
      ],
    },
    class: {
      selected: null,
      filterName: "Class",
      data: [
        "Freshman",
        "Sophomore",
        "Junior",
        "Senior",
        "Graduate Student",
        "Undergraduate Conferred",
        "Graduate Conferred",
        "Unassigned",
      ],
    },
  },
  home: {
    hometown: { selected: null, filterName: "Hometown" },
    state: {
      selected: null,
      filterName: "State",
      data: [
        "AB",
        "AE",
        "AK",
        "AL",
        "AP",
        "AR",
        "AZ",
        "BC",
        "CA",
        "CO",
        "CT",
        "DC",
        "DE",
        "FL",
        "GA",
        "GU",
        "HI",
        "IA",
        "ID",
        "IL",
        "IN",
        "KS",
        "KY",
        "LA",
        "MA",
        "MD",
        "ME",
        "MI",
        "MN",
        "MO",
        "MS",
        "MT",
        "NB",
        "NC",
        "ND",
        "NE",
        "NH",
        "NJ",
        "NM",
        "NS",
        "NV",
        "NY",
        "OH",
        "OK",
        "ON",
        "OR",
        "PA",
        "PR",
        "QC",
        "RI",
        "SC",
        "SD",
        "SK",
        "TN",
        "TX",
        "UT",
        "VA",
        "VT",
        "WA",
        "WI",
        "WV",
        "WY",
      ],
    },
    country: {
      selected: null,
      filterName: "Country",
      data: [
        "ARGENTINA",
        "AUSTRALIA",
        "AUSTRIA",
        "BAHAMAS",
        "BANGLADESH",
        "BELGIUM",
        "BERMUDA",
        "BOLIVIA (PLURINATIONAL STATE OF)",
        "BONAIRE, SINT EUSTATIUS AND SABA",
        "BRAZIL",
        "BULGARIA",
        "CAMBODIA",
        "CAMEROON",
        "CANADA",
        "CHINA",
        "CONGO, THE DEMOCRATIC REPUBLIC OF THE",
        "COSTA RICA",
        "CROATIA",
        "CYPRUS",
        "CZECHIA",
        "DENMARK",
        "DOMINICAN REPUBLIC",
        "ECUADOR",
        "EGYPT",
        "EL SALVADOR",
        "ETHIOPIA",
        "FRANCE",
        "GERMANY",
        "GHANA",
        "GREECE",
        "GUATEMALA",
        "HAITI",
        "HONDURAS",
        "HONG KONG",
        "HUNGARY",
        "INDIA",
        "INDONESIA",
        "IRELAND",
        "ISRAEL",
        "ITALY",
        "JAPAN",
        "KAZAKHSTAN",
        "KENYA",
        "KOREA, REPUBLIC OF",
        "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
        "LEBANON",
        "LITHUANIA",
        "MADAGASCAR",
        "MALAWI",
        "MALAYSIA",
        "MARSHALL ISLANDS",
        "MEXICO",
        "MOLDOVA, REPUBLIC OF",
        "MONGOLIA",
        "MOROCCO",
        "MOZAMBIQUE",
        "MYANMAR",
        "NEPAL",
        "NETHERLANDS",
        "NEW ZEALAND",
        "NIGERIA",
        "NORWAY",
        "PAKISTAN",
        "PERU",
        "PHILIPPINES",
        "POLAND",
        "ROMANIA",
        "RUSSIAN FEDERATION",
        "RWANDA",
        "SAUDI ARABIA",
        "SINGAPORE",
        "SOUTH AFRICA",
        "SPAIN",
        "SRI LANKA",
        "SWEDEN",
        "SWITZERLAND",
        "TAIWAN, PROVINCE OF CHINA",
        "TANZANIA, UNITED REPUBLIC OF",
        "THAILAND",
        "TURKEY",
        "UGANDA",
        "UKRAINE",
        "UNITED ARAB EMIRATES",
        "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND",
        "UNITED STATES OF AMERICA",
        "VIET NAM",
        "VIRGIN ISLANDS, BRITISH",
        "ZAMBIA",
        "ZIMBABWE",
      ],
    },
  },
  office: {
    department: {
      selected: null,
      filterName: "Department",
      data: [
        "Academic Success Center",
        "Admissions",
        "Art",
        "Athletics",
        "Balance & Mobility Center",
        "Biblical Studies & Christian Ministries",
        "Biology",
        "Campus Facilities Use & Planning",
        "Career & Connections Institute",
        "Center for Entrepreneurial Leadership",
        "Center for Faith and Inquiry (CFI)",
        "Center for Teaching Excellence",
        "Center for Technology Services",
        "Chemistry",
        "Christian College Consortium",
        "Christian Life and Worship",
        "Communication Arts",
        "Controller's Office",
        "Counseling Center",
        "Department of Finance",
        "Design Center",
        "Development",
        "Dining Services",
        "Economics and Business",
        "Education",
        "English Language & Literature",
        "Executive Vice President",
        "Finance and Administration",
        "Fine Arts",
        "Global Education",
        "Global Honors Institute",
        "Gordon Police",
        "Graduate Education",
        "Graduate Music",
        "Graduate Program in Financial Analysis",
        "Graduate Program in Leadership",
        "Graduate Programs",
        "Health Center",
        "History",
        "Human Resources",
        "Jenks Library",
        "Kinesiology",
        "Languages & Linguistics",
        "Mail Services",
        "Mathematics and Computer Science",
        "Music",
        "Natural Sciences, Mathematics and Computer Science",
        "Office of Communications & Marketing",
        "Office of Community Engagement",
        "Office of Institutional Research and Strategy",
        "Office of Student Life",
        "Outdoor Education",
        "Philosophy",
        "Physical Plant",
        "Physics",
        "Political Science",
        "President's Office",
        "Provost's Office",
        "Psychology",
        "Purchasing",
        "Recreation, Sport and Wellness",
        "Registrar",
        "Residence Life",
        "Social and Behavioral Science",
        "Sociology & Social Work",
        "Student Financial Services",
        "Student Life",
        "Student Services",
        "The Great Conversation",
        "Theatre",
      ],
    },
    building: {
      selected: null,
      filterName: "Building",
      data: [
        "Bromley Hall",
        "Chase Hall",
        "Conrad Hall",
        "Evans Hall",
        "Ferrin Hall",
        "Fulton Hall",
        "Grace Hall",
        "Hilton House",
        "Lewis Hall",
        "MacInnis Hall",
        "Mame Herrold Hall (5 Hull St)",
        "Nyland Hall",
        "Tavilla Hall",
        "Wilson Hall",
        "Wilson House Garage and Apartment",
      ],
    },
  },
};
